Feature/endpoints secrets
terraform-aws-modules/terraform-aws-dms pull request #27
Opened 2022-09-24 10:21 UTC by Kostavro

## Description
Adding the ability to configure aws_dms_endpoint database connection details via a SecretsManager secret.
Reference: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_endpoint#secrets_manager_access_role_arn

## Motivation and Context
This is supported in the Terraform provider and provides a nice way to securely pass the database connection details.
AWS documentation:
* https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Security.html#security_iam_secretsmanager
* https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html#vpc-endpoint

## Breaking Changes

No breaking changes.

## How Has This Been Tested?
- [X] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [X] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [X] I have executed `pre-commit run -a` on my pull request

2022-09-24 10:53 UTC, antonbabenko requested changes
I don't think introducing extra resources like this is a good idea, which should be optional (at the very least).

I recommend that you move these resources into one of the examples and show how users can use the proposed feature there. Also, please update README in the root, so users can discover it easier.

KMS and SecretManager are not prerequisites for this module to be useful AFAIK.

2022-09-24 14:55 UTC, Kostavro commented
@antonbabenko Could you please help me understand what you mean?

I am not introducing any extra resources to the module, but just introducing new optional arguments in the same way as the rest of the optional arguments in the `aws_dms_endpoint` resource.
 
I am only introducing extra resources in the example, to show how the secret functionality can be used (which I think is what you are also suggesting). I have also ran and tested the updated example, and ran this branch's configuration with my own test as well, so I am confident it works as intended.

Seeing as there are no new resources and no major changes to any of the existing ones, and nor are there any new variables, I am not sure what would you like the README in the root to say - perhaps a short excerpt of how to use this possible configuration for an endpoint?

2022-09-24 16:14 UTC, antonbabenko approved these changes
Sorry, @Kostavro ! You are right, I looked into the wrong place. :)

Let's upgrade the minimum version of the Terraform AWS provider to 4.17 in `versions.tf` in the module and in examples since the feature you added was introduced then (see [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4170-june--3-2022)), and we are good to go.

2022-09-25 06:56 UTC, Kostavro commented
Thanks @antonbabenko ! Pushed a new commit to bump the AWS provider, please review :)

2022-09-25 09:12 UTC, merged

2022-09-25 09:13 UTC, antonbabenko commented
This PR is included in version 1.6.0 :tada: